package commands

import (
	"encoding/json"
	"sort"
	"strings"
)

// Per-host renderers turn the read/write/destructive classification into safety config.
// Each emits both binary (Bash) patterns and MCP tool patterns where the host supports
// them, so an agent driving remoteok either way hits the same rails.

// claudeSettingsJSON builds the settings.json permission fragment: deny irreversible
// (canonical + alias paths + raw-api write methods + `alias set`), ask writes, allow reads.
// These are literal prefix rules — the hook is the enforcement layer (§3b hardening #1).
func claudeSettingsJSON(c classification) (string, error) {
	deny := make([]string, 0)
	ask := make([]string, 0)
	allow := make([]string, 0)
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			deny = append(deny, bashPattern(p))
		}
		deny = append(deny, mcpToolPattern(cmd.Path))
	}
	// Raw `remoteok api <METHOD> <PATH>` escape hatch: deny the write methods at the METHOD
	// position. Exact prefix rules here; the hook enforces the same gate against
	// obfuscation and path-prefixed binaries.
	for _, m := range []string{"DELETE", "PATCH", "POST", "PUT"} {
		deny = append(deny, bashPattern("api "+m))
	}
	// `remoteok alias set` can mint a shorthand that expands to a blocked command before
	// cobra parses it — deny creating new indirections.
	deny = append(deny, bashPattern("alias set"))
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			ask = append(ask, bashPattern(p))
		}
		ask = append(ask, mcpToolPattern(cmd.Path))
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			allow = append(allow, bashPattern(p))
		}
		allow = append(allow, mcpToolPattern(cmd.Path))
	}

	// ${CLAUDE_PROJECT_DIR} is the Claude runtime variable; Claude substitutes it when
	// loading the hook — it is NOT expanded here.
	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/remoteok-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{
			"deny":  deny,
			"ask":   ask,
			"allow": allow,
		},
		"hooks": map[string]any{
			// Hook both Bash and the remoteok MCP namespace.
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__remoteok__")},
		},
		"_comment": "Generated by `remoteok agent guard --host claude-code`. Save the hook script to " +
			".claude/hooks/remoteok-guard.sh (chmod +x) and merge this fragment into .claude/settings.json. " +
			"deny = irreversible operations incl. alias paths " +
			"and raw-api write methods; ask = writes; allow = reads. MCP-only operation is the hard guarantee.",
	}
	b, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}

// renderClaudeCode emits the hook script and the settings fragment as one reviewable
// document (use --write to materialize the files instead).
func renderClaudeCode(c classification) (string, error) {
	settings, err := claudeSettingsJSON(c)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString("# ----- .claude/hooks/remoteok-guard.sh (save + chmod +x) -----\n")
	out.WriteString(hookScript(c))
	out.WriteString("\n# ----- merge into .claude/settings.json -----\n")
	out.WriteString(settings)
	return out.String(), nil
}

// hookScript generates the PreToolUse hook. Commands are matched by exact SUBCOMMAND PATH
// at the command position — never by bare verbs anywhere in the line — with an optional
// path prefix before the binary so ./bin/remoteok and /usr/local/bin/remoteok are caught too.
// The raw `remoteok api <METHOD> <PATH>` escape hatch is gated at the METHOD position: only
// GET/HEAD/OPTIONS pass, case-insensitively, so a GET whose path contains "delete" stays
// allowed while de""lete-obfuscated writes are denied.
func hookScript(c classification) string {
	seenCLI := map[string]bool{}
	seenTool := map[string]bool{}
	var cliPaths, toolNames []string
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			if !seenCLI[p] {
				seenCLI[p] = true
				cliPaths = append(cliPaths, p)
			}
		}
		if t := mcpToolPattern(cmd.Path); !seenTool[t] {
			seenTool[t] = true
			toolNames = append(toolNames, t)
		}
	}
	// `alias set` can rewrite a future invocation into a blocked command before cobra
	// parses it — block minting new indirections on the Bash surface.
	if !seenCLI["alias set"] {
		cliPaths = append(cliPaths, "alias set")
	}
	sort.Strings(cliPaths)
	sort.Strings(toolNames)

	var cliArray strings.Builder
	cliArray.WriteString("blocked_cmds=(\n")
	for _, p := range cliPaths {
		safe := strings.ReplaceAll(p, "'", "'\\''")
		cliArray.WriteString("  '" + safe + "'\n")
	}
	cliArray.WriteString(")")

	var toolArray strings.Builder
	toolArray.WriteString("blocked_tools=(\n")
	for _, t := range toolNames {
		safe := strings.ReplaceAll(t, "'", "'\\''")
		toolArray.WriteString("  '" + safe + "'\n")
	}
	toolArray.WriteString(")")

	return `#!/usr/bin/env bash
# remoteok agent guard — blocks irreversible remoteok operations on the Bash and MCP
# surfaces. Generated by ` + "`remoteok agent guard`" + `; regenerate after upgrading
# remoteok so new commands (and their aliases) are covered.
#
# MATCHING STRATEGY: commands are matched by exact SUBCOMMAND PATH at the
# command position, not by bare verbs anywhere in the line. This prevents:
#   - false positives: 'remoteok messages create 42 --content "how to delete"'
#     is NOT blocked because "mail list" is not in the blocked set.
#   - false negatives: cobra alias paths are enumerated in blocked_cmds
#     alongside the canonical paths.
#
# For each blocked cli-path P, we check whether the CLEANED command string
# matches the anchored ERE:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?remoteok[[:space:]]+<P>([[:space:];&|)]|$)
# which ensures remoteok+P appears at a command position. The optional
# ([^[:space:]]*/)? prefix also catches path-invoked binaries like ./bin/remoteok
# or /usr/local/bin/remoteok, while a different binary that merely ends in "remoteok"
# (myremoteok) is NOT matched. The trailing class also covers
# "remoteok api DELETE x;true" where a separator directly follows an argument.
#
# The MCP branch is an exact set-membership check — no glob or regex.
#
# The raw "remoteok api <METHOD> <PATH>" escape hatch is gated at the METHOD
# position: only GET/HEAD/OPTIONS pass (case-insensitive). POST/PUT/PATCH/
# DELETE — and anything unrecognized, including flags-before-method tricks —
# are denied. A PATH that merely CONTAINS "delete" is not affected.
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped from
# the raw command string before pattern matching to defeat trivial tricks like
#   remoteok api DE""LETE me/messages/1
# Variable indirection (a=DELETE; remoteok api $a x) and shell aliases are NOT
# defeated — use MCP-only mode or a read-only sandbox for a hard guarantee.

# --- blocked command paths (Bash surface; canonical + cobra alias paths) ---
` + cliArray.String() + `

# --- blocked MCP tool names (exact) ---
` + toolArray.String() + `

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq needed).
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=", \047=', \134=\) and collapses
# newlines to a single line so obfuscation tricks can't split a token across
# lines. Applied in BOTH the jq and no-jq branches.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked
# remoteok subcommand path at the command position.
bash_is_blocked() {
  local cleaned="$1"
  local p
  for p in "${blocked_cmds[@]}"; do
    # Paths are "word word" so only spaces need escaping to [[:space:]]+.
    local pat
    pat=$(printf '%s' "$p" | sed 's/ /[[:space:]]+/g')
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?remoteok[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# api_is_blocked returns 0 (true) if the command invokes the raw "remoteok api"
# escape hatch with anything other than GET/HEAD/OPTIONS at the METHOD
# position. Separators are flattened first so every api invocation in a
# compound line is scanned ("remoteok api GET x;remoteok api DELETE y" cannot hide
# behind the first match).
api_is_blocked() {
  local cleaned="$1"
  local flat m
  flat=$(printf '%s' "$cleaned" | tr ';|&()' '     ')
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    case "$m" in
      [Gg][Ee][Tt]|[Hh][Ee][Aa][Dd]|[Oo][Pp][Tt][Ii][Oo][Nn][Ss]) ;; # reads pass
      *) return 0 ;;
    esac
  done < <(printf '%s' "$flat" \
    | grep -oE "(^|[[:space:]])([^[:space:]]*/)?remoteok[[:space:]]+api[[:space:]]+[^[:space:]]+" \
    | sed -E 's/^.*[[:space:]]api[[:space:]]+//')
  return 1
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: apply
# the same de-obfuscation and anchored path matching on the raw payload rather
# than a loose remoteok.*verb scan that would flag any Bash line mentioning
# remoteok+verb (e.g. "cat mail_delete.go").
if ! command -v jq >/dev/null 2>&1; then
  # Flatten JSON structure chars as well: after quote-stripping the payload
  # reads {command:remoteok api DELETE ...}, which would leave remoteok glued to
  # "command:" and never match the anchored patterns.
  flat=$(printf '%s' "$input" | tr '\n{}:,' '     ')
  cleaned=$(deobfuscate "$flat")
  if bash_is_blocked "$cleaned"; then
    deny_raw "remoteok agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  if api_is_blocked "$cleaned"; then
    deny_raw "remoteok agent guard: raw api call blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason so an interpolated value
# can never break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "remoteok agent guard: irreversible operation blocked."
    fi
    if api_is_blocked "$cleaned"; then
      deny "remoteok agent guard: raw api call blocked (only GET/HEAD/OPTIONS pass). Use dedicated commands or MCP-only mode."
    fi
    ;;
  *)
    # MCP branch: exact set-membership — no substring or regex match.
    for t in "${blocked_tools[@]}"; do
      if [ "$tool" = "$t" ]; then
        deny "remoteok agent guard: irreversible MCP tool blocked (${tool})."
      fi
    done
    ;;
esac
exit 0
`
}

// renderCodex emits a Codex config.toml: a read-only sandbox with approvals required,
// plus a commented list of the irreversible commands a reviewer should never auto-approve.
// Codex reads TOP-LEVEL sandbox_mode/approval_policy keys; an invented [sandbox] table is
// silently ignored — dead config that reads as coverage (§3b hardening #8).
func renderCodex(c classification) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by `remoteok agent guard --host codex`.\n")
	b.WriteString("# Read-only sandbox: remoteok writes require explicit approval; reads run freely.\n")
	b.WriteString("approval_policy = \"on-request\"\n")
	b.WriteString("sandbox_mode = \"read-only\"\n\n")
	b.WriteString("# Never auto-approve these irreversible remoteok operations (nor their cobra\n")
	b.WriteString("# alias paths):\n")
	for _, cmd := range c.Destructive {
		b.WriteString("#   remoteok " + cmd.Path + "\n")
	}
	b.WriteString("#\n")
	b.WriteString("# The raw escape hatch `remoteok api <METHOD> <PATH>` can call ANY endpoint —\n")
	b.WriteString("# never auto-approve an api call whose METHOD is not GET/HEAD/OPTIONS.\n")
	b.WriteString("# `remoteok alias set` can mint a shorthand for a blocked command — never\n")
	b.WriteString("# auto-approve it.\n")
	b.WriteString("\n# These writes should require approval:\n")
	for _, cmd := range c.Write {
		b.WriteString("#   remoteok " + cmd.Path + "\n")
	}
	return b.String(), nil
}

// renderOpenCode emits an opencode.json permission map: deny destructive (canonical and
// alias paths, plus raw-api write methods and `alias set`), ask writes, allow reads —
// keyed by the Bash command patterns OpenCode matches. `permission` is singular with a
// bash sub-map — the schema OpenCode actually reads (§3b hardening #8).
func renderOpenCode(c classification) (string, error) {
	perms := map[string]string{}
	for _, cmd := range c.Destructive {
		for _, p := range cmd.AllPaths() {
			perms["remoteok "+p+"*"] = "deny"
		}
	}
	for _, m := range []string{"DELETE", "PATCH", "POST", "PUT"} {
		perms["remoteok api "+m+"*"] = "deny"
	}
	perms["remoteok alias set*"] = "deny"
	for _, cmd := range c.Write {
		for _, p := range cmd.AllPaths() {
			perms["remoteok "+p+"*"] = "ask"
		}
	}
	for _, cmd := range c.Read {
		for _, p := range cmd.AllPaths() {
			perms["remoteok "+p+"*"] = "allow"
		}
	}
	root := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"permission": map[string]any{
			"bash": perms,
		},
		"_comment": "Generated by `remoteok agent guard --host opencode`. Merge into opencode.json. " +
			"deny covers alias paths, raw-api write methods, and `alias set`; these are literal " +
			"prefix rules — for obfuscation-resistant blocking use --host claude-code (hook) or MCP-only mode.",
	}
	b, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b) + "\n", nil
}
